### ISSUE TITLE
compiler source and target not passed through to maven-compiler-plugin

### ISSUE THREAD

**Issue by decathorpe** [fedora-java/xmvn#54]
This might be a side effect of https://github.com/fedora-java/xmvn/issues/34, but in xmvn 3.1.0, neither target / source levels defined in pom.xml or on the CLI (e.g. `-Dmaven.compile.source=1.6 -Dmaven.compile.target=1.6`) are passed through to the execution of `maven-compiler-plugin` anymore, which breaks at least the following packages in fedora:

- apache-commons-chain
- apache-commons-dbcp
- apache-commons-dbutils
- apache-commons-digester
- apache-commons-jexl
- apache-commons-pool
- struts

These all specify a 1.3 or 1.4 target despite using generics, which makes the `maven-compiler-plugin` execution fail with xmvn 3.1.0, but it works with xmvn 3.0.0 since it looks like it either overrides these values or passes the override from the command line through.

**Comment by mizdebsk** [comment]
Not reproducible for me. Please provide a minimal project (POM) which demonstrates the issue you are seeing with steps to reproduce the problem.

**Comment by decathorpe** [comment]
Builds were done in COPR, if you want to look at the complete build logs:

https://copr.fedorainfracloud.org/coprs/decathorpe/xmvn-3.1.0-test-builds/monitor/

For example, apache-commons-chain does this in the build:

```
%mvn_build -- -Dmaven.compile.source=1.6 -Dmaven.compile.target=1.6
```

Which expands to:

```
+ /usr/bin/python3 /usr/share/java-utils/mvn_build.py -- -Dmaven.compile.source=1.6 -Dmaven.compile.target=1.6
```

But the maven-compiler-plugin invocation from xmvn 3.1.0 fails with:

```
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ commons-chain ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 36 source files to /builddir/build/BUILD/commons-chain-1.2-src/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /builddir/build/BUILD/commons-chain-1.2-src/src/test/org/apache/commons/chain/web/portlet/MockPortletSession.java:[175,15] generics are not supported in -source 1.3
  (use -source 5 or higher to enable generics)
[ERROR] /builddir/build/BUILD/commons-chain-1.2-src/src/test/org/apache/commons/chain/web/servlet/MockHttpServletResponse.java:[210,22] generics are not supported in -source 1.3
  (use -source 5 or higher to enable generics)
[ERROR] /builddir/build/BUILD/commons-chain-1.2-src/src/test/org/apache/commons/chain/web/portlet/MockPortletRequest.java:[316,15] generics are not supported in -source 1.3
  (use -source 5 or higher to enable generics)
[ERROR] /builddir/build/BUILD/commons-chain-1.2-src/src/test/org/apache/commons/chain/web/portlet/MockPortletContext.java:[138,23] generics are not supported in -source 1.3
  (use -source 5 or higher to enable generics)
[ERROR] /builddir/build/BUILD/commons-chain-1.2-src/src/test/org/apache/commons/chain/web/servlet/MockHttpServletRequest.java:[485,22] generics are not supported in -source 1.3
  (use -source 5 or higher to enable generics)
[ERROR] /builddir/build/BUILD/commons-chain-1.2-src/src/test/org/apache/commons/chain/web/servlet/MockServletContext.java:[181,36] variable-arity methods are not supported in -source 1.3
  (use -source 5 or higher to enable variable-arity methods)
[ERROR] /builddir/build/BUILD/commons-chain-1.2-src/src/test/org/apache/commons/chain/web/servlet/MockServletContext.java:[186,12] generics are not supported in -source 1.3
  (use -source 5 or higher to enable generics)
[INFO] 7 errors 
[INFO] -------------------------------------------------------------
```

This step succeeds without errors or warnings with xmvn 3.0.0 from the fedora repos.

**Comment by mizdebsk** [comment]
This is a problem in your package. Compiler source/target for this package can be changed with maven.compile**r**.source and maven.compile**r**.target properties, while you are setting different properties (with "compile", not "compile**r**"). Closing as invalid.

**Comment by decathorpe** [comment]
Oh ... yeah I guess I'll fix that typo, and add the correct override to the rest of the broken packages.

Just to clarify, apache-commons-chain is not my package, and that typo was there since the package was first added to fedora 7 years ago:

https://src.fedoraproject.org/rpms/apache-commons-chain/c/68a55241c6d94026b7c7ef0ab011a097b9e6d190?branch=master

I just want to make sure not to break any existing packages by updating xmvn to version 3.1.0.

After adding the override without the typo to the other packages, they all build fine now.

Thanks for your help.
